[helpers]

[default]
depends = []

[default.files]
".config/Code/User" = "~/.config/Code/User"
".config/nushell" = "~/.config/nushell"
".config/nvim" = "~/.config/nvim"
".config/powershell" = "~/.config/powershell"
".config/starship.toml" = "~/.config/starship.toml"
".config/wezterm" = "~/.config/wezterm"
".ideavimrc" = "~/.ideavimrc"

[default.variables]
